# docker-compose override for local development with alosi lib
#
# specify path to local alosi library in .env file:
# e.g. "ALOSI_LOCAL_LIBRARY=/Users/me/github/alosi/alosi"
#
# usage: docker-compose -f docker-compose.yml -f docker-compose.alosi-mount.yml


version: '2'
services:
  engine:
    volumes:
      - ALOSI_LOCAL_LIBRARY:C:\Users\Admin\Anaconda3\envs\myapp\Lib\site-packages\alosi
